/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IndexScrollbar {
        "alphabet": Array<string>;
        "disableInvalidLetters": boolean;
        "exactX": boolean;
        "letterMagnification": boolean;
        "letterSpacing": number | string | null;
        "magnificationCurve": Array<number>;
        "magnificationMultiplier": number;
        "magnifyDividers": boolean;
        "navigateOnHover": boolean;
        "offsetSizeCheckInterval": number;
        "overflowDivider": string | undefined | null;
        "prioritizeHidingInvalidLetters": boolean;
        "validLetters": string[];
    }
}
declare global {
    interface HTMLIndexScrollbarElement extends Components.IndexScrollbar, HTMLStencilElement {
    }
    var HTMLIndexScrollbarElement: {
        prototype: HTMLIndexScrollbarElement;
        new (): HTMLIndexScrollbarElement;
    };
    interface HTMLElementTagNameMap {
        "index-scrollbar": HTMLIndexScrollbarElement;
    }
}
declare namespace LocalJSX {
    interface IndexScrollbar {
        "alphabet"?: Array<string>;
        "disableInvalidLetters"?: boolean;
        "exactX"?: boolean;
        "letterMagnification"?: boolean;
        "letterSpacing"?: number | string | null;
        "magnificationCurve"?: Array<number>;
        "magnificationMultiplier"?: number;
        "magnifyDividers"?: boolean;
        "navigateOnHover"?: boolean;
        "offsetSizeCheckInterval"?: number;
        "onIsActive"?: (event: CustomEvent<boolean>) => void;
        "onLetterChange"?: (event: CustomEvent<string>) => void;
        "overflowDivider"?: string | undefined | null;
        "prioritizeHidingInvalidLetters"?: boolean;
        "validLetters"?: string[];
    }
    interface IntrinsicElements {
        "index-scrollbar": IndexScrollbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "index-scrollbar": LocalJSX.IndexScrollbar & JSXBase.HTMLAttributes<HTMLIndexScrollbarElement>;
        }
    }
}
